name: special
description: Flutter Special Featurs App

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #Localization
  easy_localization: ^3.0.0
  #Splash page
  splash_screen_view: ^3.0.0
  dio: ^4.0.0
  http: ^0.13.4
  html: ^0.15.0
  # Map Locations
  google_maps_flutter: ^2.0.11
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  location: ^4.3.0
  location_web: ^3.1.1
  map: ^1.0.0
  cached_network_image: ^3.1.0
  google_api_headers: ^1.1.1
  #State managment notifier provider
  provider: ^6.0.1
  #database
  postgres: ^2.4.1+2
  #path
  path: ^1.8.0
  #search bar
  #search_widget: ^1.0.2
  #image_picker
  image_picker: ^0.8.4+2
  #Load, resize & save image to Server
  image: ^3.0.8
  #share app
  share_plus: ^3.0.4
  #Text Animation
  animated_text_kit: ^4.2.1
  #Builds indication marks for PageView.
  smooth_page_indicator: ^1.0.0+2
  #container animation
  clay_containers: ^0.3.2
  #Hive
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # For OS-specific directory paths
  #path_provider: ^2.0.5
  #Button Tab
  buttons_tabbar: ^1.3.1
  #Icons
  eva_icons_flutter: ^3.0.2
  carbon_icons: ^0.0.1+2
  #platform: :ios, '10.0'
  #Rename app icon or bundles
  rename: ^1.3.1
  #Modal Bottom Sheet
  modal_bottom_sheet: ^2.0.0
  #Settings Page
  shared_preferences: ^2.0.8
  flutter_settings_screens: ^0.3.2-null-safety
  #Animated Icon Button
  animated_icon_button: ^1.0.2
  #Dropdown list
  flutter_dropdown: ^1.0.0+hotfix.1
  #animated_progress_button: ^1.0.2+1
  youtube_player_flutter: ^8.0.0
  #Search Bar
  material_floating_search_bar: ^0.3.6
  #Security
  flutter_secure_storage: ^5.0.2
  #Paypal
  flutter_paypal: ^0.0.8
  #responsive layout for different size device_simulator
  responsive_framework: ^0.1.4
  #URL
  #url_launcher: ^6.0.12
  #Send Email in background
  #mailer: ^5.0.2
  #Google Signin
  #google_sign_in: ^5.2.1
  #firebase_auth: ^3.1.4
  #firebase_core: ^1.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
